name: cirrus
description: A sample command-line application with basic argument parsing.
version: 0.0.2
publish_to: 'none'
repository: https://github.com/cesarParra/cirrus

environment:
  sdk: ^3.8.1

dependencies:
  args: ^2.5.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
