name: cirrus
description: A sample command-line application with basic argument parsing.
version: 0.1.7
publish_to: none
repository: https://github.com/cesarParra/cirrus

environment:
  sdk: ^3.8.1

dependencies:
  args: ^2.5.0
  chalkdart: ^3.0.5
  cli_script: ^1.0.0
  fpdart: ^1.1.1
  get_it: ^8.0.3
  toml: ^0.16.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
