name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  check-version:
    runs-on: ubuntu-latest
    outputs:
      should_release: ${{ steps.check.outputs.should_release }}
      version: ${{ steps.check.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Check if version changed
        id: check
        run: |
          # Get the version from pubspec.yaml
          VERSION=$(grep "^version:" pubspec.yaml | sed 's/version: //')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          
          # Check if a tag with this version already exists
          if git rev-parse "v$VERSION" >/dev/null 2>&1; then
            echo "Version v$VERSION already exists"
            echo "should_release=false" >> $GITHUB_OUTPUT
          else
            echo "New version v$VERSION detected"
            echo "should_release=true" >> $GITHUB_OUTPUT
          fi

  update-version-file:
    needs: check-version
    if: needs.check-version.outputs.should_release == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install npm dependencies
        run: npm install
      
      - name: Generate version.dart file
        run: npm run prebuild
      
      - name: Check if version.dart changed
        id: check-changes
        run: |
          if git diff --quiet lib/src/version.dart; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Commit and push version.dart
        if: steps.check-changes.outputs.changed == 'true'
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add lib/src/version.dart
          git commit -m "chore: update version.dart to ${{ needs.check-version.outputs.version }} [skip ci]"
          git push

  build-and-release:
    needs: [check-version, update-version-file]
    if: needs.check-version.outputs.should_release == 'true'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            arch: x64
          - os: macos-latest
            platform: darwin
            arch: x64
          - os: macos-latest
            platform: darwin
            arch: arm64
          - os: windows-latest
            platform: windows
            arch: x64
    
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
      
      - name: Pull latest changes
        run: git pull origin main
      
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      
      - name: Install dependencies
        run: dart pub get
      
      - name: Build binary
        run: |
          # Set architecture-specific flags for macOS
          if [[ "${{ matrix.platform }}" == "darwin" && "${{ matrix.arch }}" == "arm64" ]]; then
            export DART_COMPILE_EXE_OPTIONS="--target-os=macos-arm64"
          elif [[ "${{ matrix.platform }}" == "darwin" && "${{ matrix.arch }}" == "x64" ]]; then
            export DART_COMPILE_EXE_OPTIONS="--target-os=macos-x64"
          fi
          
          dart compile exe bin/cirrus.dart -o cirrus-${{ matrix.platform }}-${{ matrix.arch }}${{ matrix.platform == 'windows' && '.exe' || '' }}
        shell: bash
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cirrus-${{ matrix.platform }}-${{ matrix.arch }}
          path: cirrus-${{ matrix.platform }}-${{ matrix.arch }}${{ matrix.platform == 'windows' && '.exe' || '' }}

  create-release:
    needs: [check-version, build-and-release]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=${{ needs.check-version.outputs.version }}
          
          # Create release notes
          cat > release-notes.md << EOF
          Cirrus CLI v${VERSION}
          
          ## Installation
          
          ### Using npm/npx
          \`\`\`bash
          npm install -g cirrus-for-sfdx
          # or use directly with npx
          npx cirrus-for-sfdx
          \`\`\`
          
          ### Manual Download
          Download the appropriate binary for your platform from the assets below.
          EOF
          
          # Create the release
          gh release create "v${VERSION}" \
            --title "Release v${VERSION}" \
            --notes-file release-notes.md \
            --target main
      
      - name: Upload Release Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=${{ needs.check-version.outputs.version }}
          
          # Upload all artifacts to the release
          for artifact in artifacts/*; do
            if [ -d "$artifact" ]; then
              for file in "$artifact"/*; do
                echo "Uploading $file"
                gh release upload "v${VERSION}" "$file" --clobber
              done
            fi
          done

  publish-npm:
    needs: [check-version, create-release]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Publish to npm
        run: |
          echo "Publishing version ${{ needs.check-version.outputs.version }} to npm"
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
