name: CI

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Dart
      uses: dart-lang/setup-dart@v1
      with:
        sdk: stable

    - name: Install Dart dependencies
      run: dart pub get

    - name: Run Dart tests
      run: dart test

